### ISSUE TITLE
Lambda Installer should not require a service name

### ISSUE THREAD

**Issue by chanchiem** [aws/aws-xray-java-agent#20]
The agent installer used in lambda is invoked similar to the following way:
`XRayAgentInstaller.installInLambda("servicename=MyLambdaFunction")`

In Lambda, the segment is generated on behalf of the function code by the container. The function code retrieves this segment through a concept called a Facade Segment, an immutable segment. Because the service name is never even used, the lambda installer should by default not need a service name parameter.

**Comment by willarmiros** [comment]
Removed the required parameter in #32. Resolving.
