### ISSUE TITLE
Listener should log stacktrace instead of just events during errors

### ISSUE THREAD

**Issue by chanchiem** [aws/aws-xray-java-agent#25]
The XRayListener has a catchall that logs the error of the event. We should make it print out the stack trace as well in order for us to get more informative logging information rather than just the event which is associated with the error

https://github.com/aws/aws-xray-java-agent/blob/master/aws-xray-auto-instrumentation-agent-runtime/src/main/java/com/amazonaws/xray/agent/listeners/XRayListener.java#L50

**Comment by willarmiros** [comment]
Resolved in #32 with the addition of Apache logger.
