### ISSUE TITLE
Cannot HandlerContextKey Class ENDPOINT_OVERRIDDEN

### ISSUE THREAD

**Issue by rhqnrehf** [aws/aws-xray-java-agent#83]
When used with aws sdk the above crashes.
This can be solved by lowering the version of aws sdk, but I don't think this is the correct answer.

**Comment by rhqnrehf** [comment]
NDPOINT_OVERRIDDEN Field was added from the higher version of aws sdk 1.11.872.

**Comment by willarmiros** [comment]
Thanks for raising this, it does sound like a forwards-compatibility issue with the agent's AWS SDK version. It should have been addressed by #81, and you can build the agent from scratch to get it now or wait til the next release. We are working on automating the release process to have less time & dependency surface changes between X-Ray agent releases.

**Comment by rhqnrehf** [comment]
Thank you, and sorry for not write English well lol

**Comment by willarmiros** [comment]
Fixed in 2.9.0
