### ISSUE TITLE
I hope disco works with javaagent attach method

### ISSUE THREAD

**Issue by sanghogu** [aws/aws-xray-java-agent#84]
Hello
Sorry to open the issue again

The method that javaagent is started when the app is started executes the premain service logic, but the attach method does not work normally because it enters other service logic while the application is running
Supporting the attach method makes the programming method more beautiful and free
Please review positively. Thank

**Comment by willarmiros** [comment]
Hi @rhqnrehf,

Thanks for suggesting this, could you explain a little more what the limitations are that prevent the agent from being compatible with the JDK [Attach API](https://docs.oracle.com/javase/8/docs/technotes/guides/attach/) today? The underlying disco framework [provides support](https://github.com/awslabs/disco/tree/master/disco-java-agent/disco-java-agent-inject-api) for the Attach API, so can you use that along with our agent as a workaround for now?

**Comment by rhqnrehf** [comment]
Oh, if you use OpenJDK, you cannot use general Attach API.
So, I use ea-agent-loader, and if I use this, all segments themselves are not created
