### ISSUE TITLE
Dynamic name using only disco library

### ISSUE THREAD

**Issue by rhqnrehf** [aws/aws-xray-java-agent#90]
I'm using disco for spring.
Is it possible to specify the dynamic name of disco using YML profile properties or Java config?

Example
Default Name : XRayInstrumentedService
Dynamic Name : Production??

I couldn't find it. But it seemed like there was, so I asked a question

Thank you for checking.

**Comment by willarmiros** [comment]
Hi,

I'm assuming by "only disco library" you mean you're using the Disco agent bundled with the X-Ray plugin, which is what this repo distributes. You can change the default name via the agent config file, system property, or environment variable as described in the [docs](https://docs.aws.amazon.com/xray/latest/devguide/aws-x-ray-auto-instrumentation-agent-for-java.html#XRayAutoInstrumentationAgent-Configuration).

**Comment by rhqnrehf** [comment]
Oh I can't see the system properties!!!!! Thank you
